name: Lint - Build - Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/pnpm-install

      - name: Export nx base tag
        run: export NX_BASE=$(if [ "$GITHUB_REF" = "refs/heads/main" ]; then echo "HEAD~1"; else echo "main"; fi)

      - name: Lint
        run: npx nx affected:lint --base=$NX_BASE --head=HEAD

      - name: Build
        run: npx nx affected:build --base=$NX_BASE --head=HEAD

      - name: Test
        run: npx nx  affected:test --base=$NX_BASE --head=HEAD