name: "Main branch [Lint - Build - Test]"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Dependencies
        uses: ./.github/actions/pnpm-install

      - name: Lint
        run: npx nx affected:lint --base=HEAD~1 --head=HEAD

      - name: Build
        run: npx nx affected:build --base=HEAD~1 --head=HEAD

      - name: Test
        run: npx nx  affected:test --base=HEAD~1 --head=HEAD